import * as Yup from 'yup';
// ----------------------------------------------------------------------

export const useUnitEditFormSchema = Yup.object().shape({
    txtTag: Yup.string().required('This field is required!'),
    txbQty: Yup.number().required('This field is required!'),
    ddlLocation: Yup.number().required('This field is required!'),
    ckbDownshot: Yup.boolean(),
    ddlOrientation: Yup.number().required('This field is required!'),
    ddlUnitType: Yup.number().required('This field is required!'),
    ddlControlsPreference: Yup.number().required('This field is required!'),
    txbSummerSupplyAirCFM: Yup.number().required('This field is required!'),
    txbSummerReturnAirCFM: Yup.number().required('This field is required!'),
    txbSupplyAirESP: Yup.number().required('This field is required!'),
    txbExhaustAirESP: Yup.number().required('This field is required!'),
    ckbBypass: Yup.boolean(),
    ddlUnitModel: Yup.number().required('This field is required!'),
    ddlUnitVoltage: Yup.number().required('This field is required!'),
    ckbVoltageSPP: Yup.boolean(),
    txbAltitude: Yup.number().required('This field is required!'),
    txbSummerOutdoorAirDB: Yup.number().required('This field is required!'),
    txbSummerOutdoorAirWB: Yup.number().required('This field is required!'),
    txbSummerOutdoorAirRH: Yup.number().required('This field is required!'),
    txbWinterOutdoorAirDB: Yup.number().required('This field is required!'),
    txbWinterOutdoorAirWB: Yup.number().required('This field is required!'),
    txbWinterOutdoorAirRH: Yup.number().required('This field is required!'),
    txbSummerReturnAirDB: Yup.number().required('This field is required!'),
    txbSummerReturnAirWB: Yup.number().required('This field is required!'),
    txbSummerReturnAirRH: Yup.number().required('This field is required!'),
    txbWinterReturnAirDB: Yup.number().required('This field is required!'),
    txbWinterReturnAirWB: Yup.number().required('This field is required!'),
    txbWinterReturnAirRH: Yup.number().required('This field is required!'),
    txbWinterPreheatSetpointDB: Yup.number().required('This field is required!'),
    txbSummerCoolingSetpointDB: Yup.number().required('This field is required!'),
    txbSummerCoolingSetpointWB: Yup.number().required('This field is required!'),
    txbWinterHeatingSetpointDB: Yup.number().required('This field is required!'),
    txbSummerReheatSetpointDB: Yup.number().required('This field is required!'),
    ddlOA_FilterModel: Yup.number().required('This field is required!'),
    ddlRA_FilterModel: Yup.number().required('This field is required!'),
    ddlPreheatComp: Yup.number().required('This field is required!'),
    ddlHeatExchComp: Yup.number().required('This field is required!'),
    ddlCoolingComp: Yup.number().required('This field is required!'),
    ddlHeatingComp: Yup.number().required('This field is required!'),
    txbOA_FilterPD: Yup.number().required('This field is required!'),
    txbRA_FilterPD: Yup.number().required('This field is required!'),
    ckbHeatPump: Yup.boolean(),
    ckbDehumidification: Yup.boolean(),
    ddlReheatComp: Yup.number().required('This field is required!'),
    ddlDamperAndActuator: Yup.number().required('This field is required!'),
    ddlElecHeaterVoltage: Yup.number().required('This field is required!'),
    ddlPreheatElecHeaterInstallation: Yup.number().required('This field is required!'),
    ddlHeatElecHeaterInstallation: Yup.number().required('This field is required!'),
    ckbValveAndActuator: Yup.boolean(),
    ckbDrainPan: Yup.boolean(),
    ddlPreheatCoilHanding: Yup.number().required('This field is required!'),
    ddlCoolingCoilHanding: Yup.number().required('This field is required!'),
    ddlHeatingCoilHanding: Yup.number().required('This field is required!'),
    ddlValveType: Yup.number().required('This field is required!'),
    txbPreheatSetpointDB: Yup.number().required('This field is required!'),
    txbCoolingSetpointDB: Yup.number().required('This field is required!'),
    txbCoolingSetpointWB: Yup.number().required('This field is required!'),
    txbHeatingSetpointDB: Yup.number().required('This field is required!'),
    txbReheatSetpointDB: Yup.number().required('This field is required!'),
    ckbPreheatHWC_UseCap: Yup.boolean(),
    txbPreheatHWC_Cap: Yup.number().required('This field is required!'),
    ckbPreheatHWC_UseFlowRate: Yup.boolean(),
    txbPreheatHWC_FlowRate: Yup.number().required('This field is required!'),
    ckbCoolingCWC_UseCap: Yup.boolean(),
    txbCoolingCWC_Cap: Yup.number().required('This field is required!'),
    ckbCoolingCWC_UseFlowRate: Yup.boolean(),
    txbCoolingCWC_FlowRate: Yup.number().required('This field is required!'),
    ckbHeatingHWC_UseCap: Yup.boolean(),
    txbHeatingHWC_Cap: Yup.number().required('This field is required!'),
    ckbHeatingHWC_UseFlowRate: Yup.boolean(),
    txbHeatingHWC_FlowRate: Yup.number().required('This field is required!'),
    ckbReheatHWC_UseCap: Yup.boolean(),
    txbReheatHWC_Cap: Yup.number().required('This field is required!'),
    ckbReheatHWC_UseFlowRate: Yup.boolean(),
    txbReheatHWC_FlowRate: Yup.number().required('This field is required!'),
    ddlCoolingFluidType: Yup.number().required('This field is required!'),
    ddlCoolingFluidConcentration: Yup.number().required('This field is required!'),
    txbCoolingFluidEntTemp: Yup.number().required('This field is required!'),
    txbCoolingFluidLvgTemp: Yup.number().required('This field is required!'),
    txbRefrigSuctionTemp: Yup.number().required('This field is required!'),
    txbRefrigLiquidTemp: Yup.number().required('This field is required!'),
    txbRefrigSuperheatTemp: Yup.number().required('This field is required!'),
    ddlHeatingFluidType: Yup.number().required('This field is required!'),
    ddlHeatingFluidConcentration: Yup.number().required('This field is required!'),
    txbHeatingFluidEntTemp: Yup.number().required('This field is required!'),
    txbHeatingFluidLvgTemp: Yup.number().required('This field is required!'),
    txbRefrigCondensingTemp: Yup.number().required('This field is required!'),
    txbRefrigVaporTemp: Yup.number().required('This field is required!'),
    txbRefrigSubcoolingTemp: Yup.number().required('This field is required!'),
    txbPercentCondensingLoad: Yup.number().required('This field is required!'),
    txbUnitHeightText: Yup.number(),
    txbUnitLengthText: Yup.number(),
    txbUnitWeightText: Yup.number(),
    txbUnitWidthText: Yup.number(),
    txbWinterSupplyAirCFM: Yup.number(),
    txbWinterReturnAirCFM: Yup.number(),
    ddlHandingID: Yup.number(),
    ddlSupplyAirOpeningID: Yup.number(),
    ddlSupplyAirOpeningText: Yup.string(),
    ddlExhaustAirOpeningID: Yup.number(),
    ddlExhaustAirOpeningText: Yup.string(),
    ddlOutdoorAirOpeningID: Yup.number(),
    ddlOutdoorAirOpeningText: Yup.string(),
    ddlReturnAirOpeningID: Yup.number(),
    ddlReturnAirOpeningText: Yup.string(),
  });